[build]
  command = "# no build command"
  functions = "netlify/functions"
  publish = "dist/client"

  [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  [build]
  command = "ng build --prod"
  publish = "dist/<your-angular-app>"

[plugins]
  [[plugins]]
    package = "@netlify/angular-runtime"